In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

2023-12-03 17:41:45.920374: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-03 17:41:46.014414: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-03 17:41:46.035109: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-03 17:41:46.379590: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

In [2]:
print(tf.__version__)
print(keras.__version__)

2.10.0
2.10.0


In [3]:
# Test reshape
arr = np.array(
    [[[1,2],
    [4,5],
    [7,8]],
    [[11,22],
    [44,55],
    [77,88]],
    [[13,12],
    [14,15],
    [17,18]]]
)
print(arr)
print(arr.ndim)
print(arr.shape)

a1 = arr.reshape(3,3*2)
print(a1)

[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[11 22]
  [44 55]
  [77 88]]

 [[13 12]
  [14 15]
  [17 18]]]
3
(3, 3, 2)
[[ 1  2  4  5  7  8]
 [11 22 44 55 77 88]
 [13 12 14 15 17 18]]


In [4]:
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
cpus = tf.config.experimental.list_physical_devices(device_type='CPU')
print(gpus, '\n', cpus)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')] 
 [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


2023-12-03 17:41:55.372394: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-03 17:41:55.388546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-03 17:41:55.388656: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


In [5]:
a1 = np.array(
[[
    [
        [1,2],
        [4,5],
        [7,8]
    ],
    [
        [11,22],
        [44,55],
        [77,88]
    ],
    [
        [13,12],
        [14,15],
        [17,18]
    ]
],
[
    [
        [1,2],
        [4,5],
        [7,8]
    ],
    [
        [11,22],
        [44,55],
        [77,88]
    ],
    [
        [13,12],
        [14,15],
        [17,18]
    ]
]]
)
a1.shape

(2, 3, 3, 2)

In [6]:
a2 = np.array([2,5])
a2.shape

(2,)

In [9]:
a3 = a1*a2
print(a3)
print(a3.shape)

[[[[  2  10]
   [  8  25]
   [ 14  40]]

  [[ 22 110]
   [ 88 275]
   [154 440]]

  [[ 26  60]
   [ 28  75]
   [ 34  90]]]


 [[[  2  10]
   [  8  25]
   [ 14  40]]

  [[ 22 110]
   [ 88 275]
   [154 440]]

  [[ 26  60]
   [ 28  75]
   [ 34  90]]]]
(2, 3, 3, 2)


In [10]:
dotr = np.dot(a1, a2)
print(dotr)
print(dotr.shape)
    

[[[ 12  33  54]
  [132 363 594]
  [ 86 103 124]]

 [[ 12  33  54]
  [132 363 594]
  [ 86 103 124]]]
(2, 3, 3)


In [13]:
a3 = np.array([[2,5,1], [3,4,2]])
print(a3)
print(a3.shape)

[[2 5 1]
 [3 4 2]]
(2, 3)


In [14]:
dotr = np.dot(a1, a3)
print(dotr)
print(dotr.shape)

[[[[  8  13   5]
   [ 23  40  14]
   [ 38  67  23]]

  [[ 88 143  55]
   [253 440 154]
   [418 737 253]]

  [[ 62 113  37]
   [ 73 130  44]
   [ 88 157  53]]]


 [[[  8  13   5]
   [ 23  40  14]
   [ 38  67  23]]

  [[ 88 143  55]
   [253 440 154]
   [418 737 253]]

  [[ 62 113  37]
   [ 73 130  44]
   [ 88 157  53]]]]
(2, 3, 3, 3)


In [24]:
'''
a4 = np.array([[[2,0],[5,1]], 
               [[3,3],[4,2]], 
               [[3,3],[4,2]]])
'''
a4 = np.array([[[2],[5]], 
               [[3],[4]], 
               [[3],[4]]])
print(a4)
print(a4.shape)

[[[2]
  [5]]

 [[3]
  [4]]

 [[3]
  [4]]]
(3, 2, 1)


In [25]:
dotr = np.dot(a1, a4)
print(dotr)
print(dotr.shape)

[[[[[ 12]
    [ 11]
    [ 11]]

   [[ 33]
    [ 32]
    [ 32]]

   [[ 54]
    [ 53]
    [ 53]]]


  [[[132]
    [121]
    [121]]

   [[363]
    [352]
    [352]]

   [[594]
    [583]
    [583]]]


  [[[ 86]
    [ 87]
    [ 87]]

   [[103]
    [102]
    [102]]

   [[124]
    [123]
    [123]]]]



 [[[[ 12]
    [ 11]
    [ 11]]

   [[ 33]
    [ 32]
    [ 32]]

   [[ 54]
    [ 53]
    [ 53]]]


  [[[132]
    [121]
    [121]]

   [[363]
    [352]
    [352]]

   [[594]
    [583]
    [583]]]


  [[[ 86]
    [ 87]
    [ 87]]

   [[103]
    [102]
    [102]]

   [[124]
    [123]
    [123]]]]]
(2, 3, 3, 3, 1)
