In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
data = pd.read_csv("kc_house_data.csv")
data_num = data.shape[0] 
indexes = np.random.permutation(data_num)

print(indexes)

[ 2730 20665 15040 ... 18987  9515 17090]


In [13]:
s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 3])
i = [49,0,3]
#print(s.loc[49:47])
print(s.loc[i])

49    a
0     d
3     f
dtype: object


In [4]:
import numpy as np
s = [11, 5, 8]
res = np.zeros((len(s),12))
for i, sequence in enumerate(s) :
    res[i, sequence] = 1.
    
print(res)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
